image:
  file: .gitpod.dockerfile

tasks:
   - init: |
      export POETRY_VIRTUALENVS_CREATE=false
      pip install poetry && poetry install --only main

vscode:
  extensions:
    - ms-python.python