exclude: |
  (?x)^(
      tests/shieldhit/resources/|
      tests/topas/test_topas_converter\.py|
      tests/fluka/expected_fluka_output/fl_sim\.py|
      tests/shieldhit/test_shieldhit_config_mappings\.py|
      .*\.dat$|
      .*\.cfg$|
      .*\.json$|
      .*\.md$|
      .*\.yaml$|
      .*\.yml$
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      # - id: check-docstring-first
      # - id: double-quote-string-fixer
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        name: ruff check
        args: [ --fix ]
      - id: ruff-format
        name: ruff format
