[tool.poetry]
name = "converter"
version = "1.0.0"
description = "Yet Another Particle Transport IDE - converter"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
