from typing import List

DEFAULT_PARTICLE_ID: int = 2
DEFAULT_PARTICLE_A: int = 1
DEFAULT_PARTICLE_Z_FROM_A: bool = True
DEFAULT_BEAM_POSITION: List = [0, 0, 0]
DEFAULT_BEAM_DIRECTION: List = [0, 0, 1]
