name: pre-commit
permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:

jobs:
  pre-commit:
    name: Run Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --with test --no-interaction

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files --show-diff-on-failure
